force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>A text or lookup field to store the name of the company where the job application is being sent.</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a Contact that represents the main point of contact for the job. This could be a recruiter or employee at the company.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/addApplicationPrimaryContact.cls
public with sharing class addApplicationPrimaryContact {
        public static void addPrimaryContactToJobApplications(List<Job_Application__c> jobApps) {            //Set<Id> accountIds = new Set<Id>();
            Map<Id,Id> appIdToAccountMap = new Map<Id,Id>();
            for (Job_Application__c jobApp : jobApps) {
                if(jobApp.Company_Name__c != null) {
                    appIdToAccountMap.put(jobApp.Id,jobApp.Company_Name__c);
                    }
                }

            List<Contact> contactMap = [SELECT AccountId FROM Contact WHERE AccountId = :appIdToAccountMap.values()];
            
            Map<Id,Contact> acctToContactId = new Map<Id,Contact>();

            for (Contact con : contactMap) {
                if(!acctToContactId.keySet().contains(con.AccountId)) {
                    acctToContactId.put(con.AccountId,con);
                    }
            }

            for (Job_Application__c jobApp : jobApps) {
                if(jobApp.Company_Name__c != null && acctToContactId.containskey(jobApp.Company_Name__r.Id)) {
                   jobApp.Primary_Contact__c = acctToContactId.get(jobApp.Company_Name__r.Id).Id;
            }
        }
    }
}